In [3]:
import sys
sys.path.append("../..")

from app.components.extract_data  import * # Readind and initialization of the datasets
from pandas import DataFrame
from app.components.extract_data.dataframes.dictionaries.nutrients import nutrients
from app.components.extract_data.dataframes.get_nutrition import get_nutrients, get_nutrients_dif

import numpy as np

Reading the datasets
Creating person ID
Removing unnecessary columns
Convert codes into readable

In [4]:
dfConsumo.head()

NameError: name 'dfConsumo' is not defined

In [3]:
## Get the dataframe with the sum of each nutrients consumed by each person
dfNutrients = get_nutrients(dfConsumo)
dfNutrients.head()

,PESSOA,ENERGIA_KCAL,CHOTOT,PTN,LIP,FIBRA,COLEST,CALCIO,SODIO,POTASSIO,...,RIBOFLAVINA,NIACINA,PIRIDOXAMINA,COBALAMINA,VITC,VITA_RAE,COBRE,FOLATO,FOSFORO,ZINCO
0,110000016.0#1.0#12.0#2.0,1710.90,201.76700,93.79800,59.77300,5.64800,345.50300,218.4860,1532.82000,1420.46300,...,0.29400,36.18300,0.15300,1.250,32.316,158.0360,0.58700,120.33600,859.45900,6.04400
1,110000016.0#1.0#12.0#3.0,1447.55,211.72850,66.35600,38.40600,6.69200,233.74300,181.5510,1124.75600,1470.25250,...,0.23100,24.33000,0.11100,0.931,13.780,64.9340,0.44800,97.87300,624.65000,4.20600
2,110000016.0#1.0#13.0#1.0,1654.63,214.56008,72.97622,63.32802,31.54542,184.57752,438.5491,2232.17768,3639.49704,...,0.56212,20.06438,0.47574,1.029,67.380,373.1730,1.68996,324.07148,978.20546,7.35082
3,110000016.0#1.0#2.0#1.0,1517.45,222.61650,62.84800,47.73160,26.33600,84.57700,211.9484,1679.27420,1827.59990,...,1.11200,8.82000,0.56100,2.805,7.803,570.9620,1.50800,203.46180,689.42920,10.94800
4,110000016.0#1.0#2.0#2.0,1307.95,206.18650,42.30650,40.17660,23.36950,46.93100,199.1539,1411.21920,1418.90640,...,0.99450,5.90100,0.54050,1.545,6.480,481.5435,1.32150,192.10080,511.20520,6.86450

In [4]:
## Person is the preprossed dfNutrients with more columns
## UF
## RENDA_TOTAL
## EER
## GENDER (SOON)
## AGE (SOON)
## HEIGHT (SOON)
## WEIGHT (SOON)
dfPerson.head()

,PESSOA,ENERGIA_KCAL,CHOTOT,PTN,LIP,FIBRA,COLEST,CALCIO,SODIO,POTASSIO,...,VITC,VITA_RAE,COBRE,FOLATO,FOSFORO,ZINCO,UF,RENDA_TOTAL,ESTRATO_POF,EER
0,110000016.0#1.0#12.0#2.0,1710.90,201.76700,93.79800,59.77300,5.64800,345.50300,218.4860,1532.82000,1420.46300,...,32.316,158.0360,0.58700,120.33600,859.45900,6.04400,11.0,4353.51,1101.0,2022.16
1,110000016.0#1.0#12.0#3.0,1447.55,211.72850,66.35600,38.40600,6.69200,233.74300,181.5510,1124.75600,1470.25250,...,13.780,64.9340,0.44800,97.87300,624.65000,4.20600,11.0,4353.51,1101.0,1940.10
2,110000016.0#1.0#13.0#1.0,1654.63,214.56008,72.97622,63.32802,31.54542,184.57752,438.5491,2232.17768,3639.49704,...,67.380,373.1730,1.68996,324.07148,978.20546,7.35082,11.0,1367.63,1101.0,2003.41
3,110000016.0#1.0#2.0#1.0,1517.45,222.61650,62.84800,47.73160,26.33600,84.57700,211.9484,1679.27420,1827.59990,...,7.803,570.9620,1.50800,203.46180,689.42920,10.94800,11.0,3855.34,1101.0,2388.84
4,110000016.0#1.0#2.0#2.0,1307.95,206.18650,42.30650,40.17660,23.36950,46.93100,199.1539,1411.21920,1418.90640,...,6.480,481.5435,1.32150,192.10080,511.20520,6.86450,11.0,3855.34,1101.0,1765.61

In [5]:
## DataFrame with the actual nutrition and the difference with optimal nutrition by nutrient
dfNutrientsDif = get_nutrients_dif(dfPerson)
dfNutrientsDif.head()

,PESSOA,ENERGIA_KCAL,CHOTOT,PTN,LIP,FIBRA,COLEST,CALCIO,SODIO,POTASSIO,...,RIBOFLAVINA_DIFF,NIACINA_DIFF,PIRIDOXAMINA_DIFF,COBALAMINA_DIFF,VITC_DIFF,VITA_RAE_DIFF,COBRE_DIFF,FOLATO_DIFF,FOSFORO_DIFF,ZINCO_DIFF
0,110000016.0#1.0#12.0#2.0,1710.90,201.76700,93.79800,59.77300,5.64800,345.50300,218.4860,1532.82000,1420.46300,...,-0.70600,24.68300,-0.94700,-0.750,-33.784,-401.9640,-0.11300,-201.66400,210.45900,-1.95600
1,110000016.0#1.0#12.0#3.0,1447.55,211.72850,66.35600,38.40600,6.69200,233.74300,181.5510,1124.75600,1470.25250,...,-0.76900,12.83000,-0.98900,-1.069,-52.320,-495.0660,-0.25200,-224.12700,-24.35000,-3.79400
2,110000016.0#1.0#13.0#1.0,1654.63,214.56008,72.97622,63.32802,31.54542,184.57752,438.5491,2232.17768,3639.49704,...,-0.43788,8.56438,-0.62426,-0.971,1.280,-186.8270,0.98996,2.07148,329.20546,-0.64918
3,110000016.0#1.0#2.0#1.0,1517.45,222.61650,62.84800,47.73160,26.33600,84.57700,211.9484,1679.27420,1827.59990,...,0.11200,-2.68000,-0.53900,0.805,-58.297,10.9620,0.80800,-118.53820,40.42920,2.94800
4,110000016.0#1.0#2.0#2.0,1307.95,206.18650,42.30650,40.17660,23.36950,46.93100,199.1539,1411.21920,1418.90640,...,-0.00550,-5.59900,-0.55950,-0.455,-59.620,-78.4565,0.62150,-129.89920,-137.79480,-1.13550